/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Programa3;

import DAOs.CarreraDAO;
import DTOs.CarreraDTO;
import ExcepcionNegocio.NegocioException;
import Interfaces.ICarreraNegocio;
import Negocio.CarreraNegocio;
import Utilerias.RenderTabla;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oribiel
 */
public class AdminCarreras extends javax.swing.JPanel {

    ICarreraNegocio carreraNegocio;

    public AdminCarreras() {
        initComponents();
        this.carreraNegocio = new CarreraNegocio(new CarreraDAO());
        llenarTablaCarreras();
    }

    public void mostrarPanel(JPanel p) {

        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(385, 400);
        frame.setLocationRelativeTo(null);
        frame.add(p);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnNuevaCarrera = new javax.swing.JButton();
        tfBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarAlumno = new javax.swing.JButton();

        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 410));

        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tiempo limite", "Color", "Editar", "Eliminar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnNuevaCarrera.setBackground(new java.awt.Color(0, 102, 204));
        btnNuevaCarrera.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaCarrera.setText("Nuevo carrera");
        btnNuevaCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCarreraActionPerformed(evt);
            }
        });

        tfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Buscar carrera");

        btnBuscarAlumno.setBackground(new java.awt.Color(0, 102, 204));
        btnBuscarAlumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAlumno.setText("Buscar");
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnNuevaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(239, 239, 239))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCarreraActionPerformed

        crearCarrera p = new crearCarrera();
        mostrarPanel(p);

    }//GEN-LAST:event_btnNuevaCarreraActionPerformed

    private void tfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarActionPerformed

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        try {
            String nombreCarrera = tfBuscar.getText().trim();
            CarreraDTO carrera = carreraNegocio.buscarCarreraPorNombre(nombreCarrera);

            if (carrera != null) {
                obtenerDatos(carrera);
            } else {
                JOptionPane.showMessageDialog(this, "Por favor ingrese una carrera válida.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al buscar la carrera.", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); // Opcional: útil para depurar
        }
    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int column = this.jTable2.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / this.jTable2.getRowHeight();

        if (row < this.jTable2.getRowCount() && row >= 0 && column < this.jTable2.getColumnCount() && column >= 0) {
            Object value = this.jTable2.getValueAt(row, column);

            if (value instanceof JButton) {
                JButton boton = (JButton) value;
                Long carreraid = (Long) this.jTable2.getValueAt(row, 0);

                if (boton.getText().equals("Editar")) {
                    editarCarrera(carreraid);
                } else if (boton.getText().equals("Eliminar")) {
                    eliminarCarrera(carreraid);
                }
            }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void editarCarrera(Long carreraid) {
        CarreraDTO carrera = carreraNegocio.buscarCarreraPorId(carreraid);
        if (carrera != null) {

            crearCarrera p = new crearCarrera();
            p.cargarDatosCarrera(carrera);
            mostrarPanel(p);

        } else {
            JOptionPane.showMessageDialog(this, "No se encontro la carrera.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void eliminarCarrera(Long carreraid) {
        CarreraDTO carrera = carreraNegocio.buscarCarreraPorId(carreraid);
        if (carrera != null) {
            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de que desea eliminar la carrera " + carrera.getNombre() + "?",
                    "Confirmación de eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (opcion == JOptionPane.YES_OPTION) {
                carreraNegocio.eliminarCarreraPorId(carreraid);
                JOptionPane.showMessageDialog(this, "Carrera eliminada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                llenarTablaCarreras();
            } else {
                JOptionPane.showMessageDialog(this, "Eliminación cancelada.", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Carrera no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void obtenerDatos(CarreraDTO carrera) {
        //esto llena los datos del buscar
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0);

        JButton[] botones = generarBotones(carrera.getId());

        modelo.addRow(new Object[]{
            carrera.getId(),
            carrera.getNombre(),
            carrera.getTiempoLimite(),
            carrera.getColor(),
            botones[0],
            botones[1]
        });
    }

    private JButton[] generarBotones(Long alumnoid) {

        JButton btnEditar = new JButton("Editar");
        btnEditar.setName("M");
        JButton btnEliminar = new JButton("Eliminar");
        btnEliminar.setName("E");

        return new JButton[]{btnEditar, btnEliminar};
    }

    public void llenarTablaCarreras() {

        List<CarreraDTO> carreras = carreraNegocio.obtenerCarrerasTabla();
        if (carreras == null || carreras.isEmpty()) {
            return;
        }
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelo.setColumnIdentifiers(new Object[]{"ID", "Nombre", "TiempoLimite", "Color", "Editar", "Eliminar"});
        for (CarreraDTO carrera : carreras) {
            JButton[] btn = generarBotones(carrera.getId());

            modelo.addRow(new Object[]{
                carrera.getId(),
                carrera.getNombre(),
                carrera.getTiempoLimite(),
                carrera.getColor(),
                btn[0], // Botón Editar
                btn[1] // Botón Eliminar
            });
        }
    
        jTable2.setModel(modelo);

        jTable2.getColumnModel().getColumn(0).setMinWidth(0);
        jTable2.getColumnModel().getColumn(0).setMaxWidth(0);

        jTable2.getColumn("Editar").setCellRenderer(new RenderTabla());
        jTable2.getColumn("Eliminar").setCellRenderer(new RenderTabla());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton btnNuevaCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField tfBuscar;
    // End of variables declaration//GEN-END:variables
}
