/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Programa3;

import DAOs.LaboratorioDAO;
import DTOs.LaboratorioDTO;
import Interfaces.ILaboratorioNegocio;
import Negocio.LaboratorioNegocio;
import Utilerias.RenderTabla;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oribiel
 */
public class AdminLaboratorios extends javax.swing.JPanel {

    ILaboratorioNegocio laboratorioNegocio;

    public AdminLaboratorios() {
        this.laboratorioNegocio = new LaboratorioNegocio(new LaboratorioDAO());
        initComponents();
        llenarTablaLaboratorio();
    }

    public void llenarTablaLaboratorio() {

        List<LaboratorioDTO> laboratorios = laboratorioNegocio.obtenerLaboratoriosTabla();
        if (laboratorios == null || laboratorios.isEmpty()) {
            return;
        }
        DefaultTableModel modelo = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelo.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Hora Apertura", "Hora cierre", "Editar", "Eliminar"});
        for (LaboratorioDTO laboratorio : laboratorios) {
            JButton[] btn = generarBotones(laboratorio.getId());

            modelo.addRow(new Object[]{
                laboratorio.getId(),
                laboratorio.getNombreLab(),
                laboratorio.getHoraInicio(),
                laboratorio.getHoraFin(),
                btn[0], // Botón Editar
                btn[1] // Botón Eliminar
            });
        }

        jTable1.setModel(modelo);

        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);

        jTable1.getColumn("Editar").setCellRenderer(new RenderTabla());
        jTable1.getColumn("Eliminar").setCellRenderer(new RenderTabla());
    }

    private JButton[] generarBotones(Long alumnoid) {

        JButton btnEditar = new JButton("Editar");
        btnEditar.setName("M");
        JButton btnEliminar = new JButton("Eliminar");
        btnEliminar.setName("E");

        return new JButton[]{btnEditar, btnEliminar};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNuevoLaboratorio = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Hora apertura", "Hora cierre", "Editar", "Eliminar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnNuevoLaboratorio.setBackground(new java.awt.Color(0, 102, 204));
        btnNuevoLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoLaboratorio.setText("Nuevo Laboratorio");
        btnNuevoLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLaboratorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevoLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnNuevoLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLaboratorioActionPerformed
        ControlNavegacion.ControlNavegacion.mostrarAgregarLaboratorio();
    }//GEN-LAST:event_btnNuevoLaboratorioActionPerformed

        public void mostrarPanel(JFrame p) {

        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(385, 400);
        frame.setLocationRelativeTo(null);
        frame.add(p);
        frame.setVisible(true);
    }

    
    public void editarLaboratorio(Long idlab){

    }
    
    public void eliminarLaboratorio(Long idlab){
        
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int column = this.jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / this.jTable1.getRowHeight();

        if (row < this.jTable1.getRowCount() && row >= 0 && column < this.jTable1.getColumnCount() && column >= 0) {
            Object value = this.jTable1.getValueAt(row, column);

            if (value instanceof JButton) {
                JButton boton = (JButton) value;
                Long labid = (Long) this.jTable1.getValueAt(row, 0);

                if (boton.getText().equals("Editar")) {
                    editarLaboratorio(labid);
                } else if (boton.getText().equals("Eliminar")) {
                    eliminarLaboratorio(labid);
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoLaboratorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
