/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Programa3;

/**
 *
 * @author Jack Murrieta
 */
public class NuevoSoftware extends javax.swing.JPanel {

    /**
     * Creates new form EquipoSeleccionado
     */
    public NuevoSoftware() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIP2 = new javax.swing.JLabel();
        lblIP4 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNombreSw = new javax.swing.JTextField();
        txtDescripcionSw = new javax.swing.JTextField();
        btnGuardarCambios = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 1, 0));

        lblIP2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblIP2.setForeground(new java.awt.Color(30, 47, 86));
        lblIP2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP2.setText("Nombre software:");
        jPanel1.add(lblIP2);

        lblIP4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblIP4.setForeground(new java.awt.Color(30, 47, 86));
        lblIP4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP4.setText("Descripcion:");
        jPanel1.add(lblIP4);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, 390));

        lblTitulo1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(30, 47, 86));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Nuevo Software");
        add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 464, 81));

        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 0, 30));
        jPanel2.add(txtNombreSw);
        jPanel2.add(txtDescripcionSw);

        btnGuardarCambios.setText("Guardar Software");
        jPanel2.add(btnGuardarCambios);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 340, 350));

        btnRegresar.setText("Regresar");
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIP2;
    private javax.swing.JLabel lblIP4;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTextField txtDescripcionSw;
    private javax.swing.JTextField txtNombreSw;
    // End of variables declaration//GEN-END:variables
}
