/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Programa3;

/**
 *
 * @author Jack Murrieta
 */
public class OpcionRealizarComputo extends javax.swing.JPanel {

    /**
     * Creates new form EquipoSeleccionado
     */
    public OpcionRealizarComputo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnAsignarSw = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(30, 47, 86));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Opcion a realizar");
        add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 28, 464, 81));

        btnEditar.setText("Editar Equipo");
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 320, 60));

        btnRegresar.setText("Regresar");
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 30));

        btnAsignarSw.setText("Asignar Softwares");
        add(btnAsignarSw, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 340, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarSw;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblTitulo1;
    // End of variables declaration//GEN-END:variables
}
